### ISSUE TITLE
Upgrade Apache POI

### ISSUE THREAD

**Issue by john-oi** [TouK/excel-export#23]
Any plans to upgrade Apache POI to 3.10 FINAL?  I'm seeing some significant performance improvements using it . . .

**Comment by hansgru** [comment]
+1 please update the the latest available POI and make a new release.

**Comment by sw360cab** [comment]
#33 I've just pushed a pull request for that

**Comment by sw360cab** [comment]
This issue can be marked as closed with merge and version 0.2.2
