### ISSUE TITLE
how to export domain's nested properties (list/individual) 

### ISSUE THREAD

**Issue by hkg25** [TouK/excel-export#40]
User domain class have list of address like

User {
  List<Address> addresses
}

Address {
String city
}

Need city in with properties 
 
def withProperties = ['firstName', 'lastName', 'email','phoneNumber','addresses.first().city'] // not working

**Comment by jakubnabrdalik** [comment]
That's because you cannot call a method in a string. Remove "first()" or add your own getter implementation if you need to get the first one.
