### ISSUE TITLE
UrlMappings should not be packaged with plugin

### ISSUE THREAD

**Issue by houbie** [TouK/excel-export#44]
The UrlMappings in the default package should be excluded from the plugin jar.
It overwrites url mappings of the application. See also https://github.com/grails/grails-core/issues/9706

**Comment by graemerocher** [comment]
since they are in a package no I  am not sure it is necessary from excluding them from being packaged, although we should update the documentation if this is the way we go. However plugin authors should remove the file if they don't plan to expose URL mappings.

**Comment by dvisco** [comment]
Is there any way to disable these mappings? as it stands the mappings are
```
		"/$controller/$action?/$id?"{
			constraints {
				// apply constraints here
			}
		}

		"/"(view:"/index")
		"500"(view:'/error')
```
If you utilize this plugin this mapping expose all controller actions which is problematic. Is there a way to ignore this mapping?
