### ISSUE TITLE
Ambiguous method overloading for method java.io.File#<init>.

### ISSUE THREAD

**Issue by fernandoiwamoto** [TouK/excel-export#50]
Using grails 3.1.8 and I just added it into my grails project and the error poped up.

Caused by GroovyRuntimeException: Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
	[class java.lang.String]
	[class java.net.URI]
->>   59 | copyAndLoad in pl.touk.excel.export.XlsxExporter
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     10 | <init>    in pl.touk.excel.export.WebXlsxExporter

I use to simplest example and I got this.

**Comment by dpcasady** [comment]
Thanks, will fix.
