### ISSUE TITLE
Cannot deploy app when plugin is included: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal

### ISSUE THREAD

**Issue by benorama** [TouK/excel-export#8]
When using the app with excel-report plugin locally (Mac OSX, Oracle JVM 1.7.0_11 ), everything works fine.

But when we deploy the war on Ubuntu 12.04 (Oracle JVM 1.7.0_25-b30), deployment fails with "java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal".
It looks like this is related to 'xml-apis'.

Any idea?

**Comment by pozuelog** [comment]
I had same problem (Ubuntu + Sun Java 6 + tomcat6) and I solved it by setting:

```
inherits("global") {
        // specify dependency exclusions here; for example, uncomment this to disable ehcache:
        // excludes 'ehcache'
        //This is needed in order to solve bug on excel-export (POI, xerces, etc). Bug info in: https://github.com/TouK/excel-export/issues/8
        excludes "xercesImpl"
    }
```

in my BuildConfig.groovy
